### ISSUE TITLE
Insert Query Error

### ISSUE THREAD

**Issue by jbeardon** [JavanXD/ya-pihole-list#1]
There appears to be an  issue with the insert query:

Info: Download latest adlists list to /home/pi/adlists.list.updater
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1620  100  1620    0     0    189      0  0:00:08  0:00:08 --:--:--   363
Info: Adding content of /home/pi/adlists.list.updater into gravity database
Warning: Some warnings in table adlist in database /etc/pihole/gravity.db\n  /ho                                                      me/pi/adlists.list.updater.tmp:1: expected 6 columns but found 5 - filling the r                                                      est with NULL
/home/pi/adlists.list.updater.tmp:1: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:2: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:2: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:3: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:3: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:4: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:4: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:5: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:5: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:6: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:6: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:7: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:7: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:8: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:8: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:9: expected 6 columns but found 5 - filling th                                                      e rest with NULL
/home/pi/adlists.list.updater.tmp:9: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:10: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:10: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:11: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:11: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:12: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:12: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:13: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:13: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:14: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:14: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:15: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:15: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:16: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:16: INSERT failed: datatype mismatch
/home/pi/adlists.list.updater.tmp:17: expected 6 columns but found 5 - filling t                                                      he rest with NULL
/home/pi/adlists.list.updater.tmp:17: INSERT failed: datatype mismatch
Info: Update Gravity because of the changes to the gravity.db
  [i] Neutrino emissions detected...

**Comment by JavanXD** [comment]
I'll fix it soon. it is only a warning therefore the import should have worked.

**Comment by jbeardon** [comment]
Unfortunately, they do seem to be preventing the list imports - nothing in adlists.list.updater has appeared (that was not already there)

**Comment by JavanXD** [comment]
thank you! i fixed this issue. importing from adlist should work now.

**Comment by JavanXD** [comment]
If you try to add a list which is already in the database you will receive the following warnings:
```
Info: Adding content of /home/pi/adlists.list.updater into gravity database
Warning: Some warnings in table adlist in database /etc/pihole/gravity.db:
/home/pi/adlists.list.updater.tmp:1: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:2: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:3: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:4: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:5: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:6: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:7: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:8: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:9: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:10: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:11: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:12: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:13: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:14: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:15: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:16: INSERT failed: UNIQUE constraint failed: adlist.address
/home/pi/adlists.list.updater.tmp:17: INSERT failed: UNIQUE constraint failed: adlist.address
```

**Comment by TheDevRo** [comment]
Im seeing this issue again on new installs on Raspberry Pi OS. Any tips?
