### ISSUE TITLE
Remove dbl.oisd.nl from your master list

### ISSUE THREAD

**Issue by kiloforce** [JavanXD/ya-pihole-list#10]
I don't know if this is a temporary issue, or permanent, but there appears to be an issue with dbl.oisd.nl.  May want to remove that from your master list.

Adlist:
```
# Ads, Mobile Ads, Phishing, Malvertising, Malware, Spyware, Ransomware, CryptoJacking and some Telemetry, Analytics, Tracking
https://dbl.oisd.nl/
```

Log:
```
  [i] Target: https://dbl.oisd.nl/
  [✗] Status: https://dbl.oisd.nl/ (410)
  [✗] List download failed: no cached list available
```

![image](https://github.com/JavanXD/ya-pihole-list/assets/433058/573cea72-319b-4eee-afbf-563ade27036a)

**Comment by JavanXD** [comment]
Was fixed with latest update, thanks!

**Comment by kiloforce** [comment]
Thanks!
