### ISSUE TITLE
Add YouTube ad-blocking

### ISSUE THREAD

**Issue by JanJans640** [JavanXD/ya-pihole-list#12]
Hi,

Thanks for your addlist + updater.
Fantastic job.
Now my question, is it possible to add a YouTube ad-blocking list?

Thanks in advanced.
Jan.

**Comment by JavanXD** [comment]
Unfortunately this is a general "bigger" issue with is showcasing the limits of a DNS blocking service such as PiHole. Simply you can't. Because youtube is using the same DNS for the videos as for the ads.
