### ISSUE TITLE
Updated Pihole adlist format

### ISSUE THREAD

**Issue by RobTulloch** [JavanXD/ya-pihole-list#5]
The pihole adlist format now expects 10 columns and the INSERT breaks on the NULL values that get autofilled.
Line 73 in adlists-updater.sh needs to be updated to read:
` echo "${rowid},\"${domain}\",1,${timestamp},${timestamp},\"Added by Updater\",,0,0,0" >> "${tmpFile}"`

**Comment by JavanXD** [comment]
Thanks, updated it with https://github.com/JavanXD/ya-pihole-list/commit/910094847c5e7669150ed2613c02ad6138dc6a00
